# Generated by Django 6.0.1 on 2026-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='approved_by',
            field=models.CharField(choices=[('resident', 'Resident'), ('guard', 'Guard')], default='resident', max_length=15),
        ),
    ]
